### PR TITLE
Custom object support

### PR DESCRIPTION
**Pull request by alex-wood**
No spec is included in this branch as custom objects don’t appear to be enabled on the test account. I’ll gladly add a corresponding spec for this feature if the custom objects feature can be turned on.

### CODE REVIEW

**Comment by ifightcrime** [comment]
:+1:

**Comment by raszi** [comment]
I need to get a proper test account from Marketo somehow, then we can enable the custom objects feature.

**Comment by alex-wood** [comment]
Great! I'll look into it as well.

**Comment by lpopa** [comment]
I've added tests for @alex-wood's changes and submitted a pull request for it. My company has a Marketo account that has custom objects enabled, so it was easy for me to fill in the missing tests.

**Comment by alex-wood** [comment]
These changes have been moved into #9.

**Pull request closed without merging**
